client_config_backend: file
client_config:
    client_id: 166823270725-7cselr3u56m9ssk4kfpnoo8cei0l00ns.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive